import tkinter as tk
from tkinter import messagebox, filedialog
from tkinter import ttk

class RecipeConfigurator:
    def __init__(self, root):
        self.root = root
        self.root.title("ItemsAdder Recipe Configurator by EnderAzure")

        self.crafting_grid = [['' for _ in range(3)] for _ in range(3)]
        self.ingredients = {}
        self.valid_item_ids = self.get_valid_item_ids()
        self.create_widgets()

    def get_valid_item_ids(self):
        # Eine Liste der gültigen Item-IDs aus der Minecraft Spigot Material API
        return {
            "ACACIA_BOAT", "ACACIA_BUTTON", "ACACIA_DOOR", "ACACIA_FENCE", "ACACIA_FENCE_GATE",
            "ACACIA_LEAVES", "ACACIA_LOG", "ACACIA_PLANKS", "ACACIA_PRESSURE_PLATE",
            "ACACIA_SAPLING", "ACACIA_SIGN", "ACACIA_SLAB", "ACACIA_STAIRS", "ACACIA_TRAPDOOR",
            "ACACIA_WALL_SIGN", "ACACIA_WOOD", "ACTIVATOR_RAIL", "AIR", "ALLIUM", "AMETHYST_BLOCK",
            "AMETHYST_CLUSTER", "ANCIENT_DEBRIS", "ANDESITE", "ANDESITE_SLAB", "ANDESITE_STAIRS",
            "ANDESITE_WALL", "ANVIL", "APPLE", "ARMOR_STAND", "ARROW", "AXOLOTL_BUCKET",
            "AXOLOTL_SPAWN_EGG", "AZALEA", "AZALEA_LEAVES", "AZURE_BLUET", "BAKED_POTATO",
            "BAMBOO", "BARREL", "BARRIER", "BASALT", "BAT_SPAWN_EGG", "BEACON", "BEDROCK",
            "BEE_NEST", "BEE_SPAWN_EGG", "BEEF", "BEEHIVE", "BEETROOT", "BEETROOT_SEEDS",
            "BEETROOT_SOUP", "BELL", "BIRCH_BOAT", "BIRCH_BUTTON", "BIRCH_DOOR", "BIRCH_FENCE",
            "BIRCH_FENCE_GATE", "BIRCH_LEAVES", "BIRCH_LOG", "BIRCH_PLANKS", "BIRCH_PRESSURE_PLATE",
            "BIRCH_SAPLING", "BIRCH_SIGN", "BIRCH_SLAB", "BIRCH_STAIRS", "BIRCH_TRAPDOOR",
            "BIRCH_WALL_SIGN", "BIRCH_WOOD", "BLACK_BANNER", "BLACK_BED", "BLACK_CANDLE",
            "BLACK_CARPET", "BLACK_CONCRETE", "BLACK_CONCRETE_POWDER", "BLACK_DYE",
            "BLACK_GLAZED_TERRACOTTA", "BLACK_SHULKER_BOX", "BLACK_STAINED_GLASS",
            "BLACK_STAINED_GLASS_PANE", "BLACK_TERRACOTTA", "BLACK_WOOL", "BLAZE_POWDER",
            "BLAZE_ROD", "BLAZE_SPAWN_EGG", "BLUE_BANNER", "BLUE_BED", "BLUE_CANDLE",
            "BLUE_CARPET", "BLUE_CONCRETE", "BLUE_CONCRETE_POWDER", "BLUE_DYE",
            "BLUE_GLAZED_TERRACOTTA", "BLUE_ICE", "BLUE_ORCHID", "BLUE_SHULKER_BOX",
            "BLUE_STAINED_GLASS", "BLUE_STAINED_GLASS_PANE", "BLUE_TERRACOTTA", "BLUE_WOOL",
            "BONE", "BONE_BLOCK", "BONE_MEAL", "BOOK", "BOOKSHELF", "BOW", "BOWL", "BRAIN_CORAL",
            "BRAIN_CORAL_BLOCK", "BRAIN_CORAL_FAN", "BRAIN_CORAL_WALL_FAN", "BREAD", "BREWING_STAND",
            "BRICK", "BRICK_SLAB", "BRICK_STAIRS", "BRICK_WALL", "BRICKS", "BROWN_BANNER",
            "BROWN_BED", "BROWN_CANDLE", "BROWN_CARPET", "BROWN_CONCRETE", "BROWN_CONCRETE_POWDER",
            "BROWN_DYE", "BROWN_GLAZED_TERRACOTTA", "BROWN_MUSHROOM", "BROWN_MUSHROOM_BLOCK",
            "BROWN_SHULKER_BOX", "BROWN_STAINED_GLASS", "BROWN_STAINED_GLASS_PANE",
            "BROWN_TERRACOTTA", "BROWN_WOOL", "BUBBLE_COLUMN", "BUBBLE_CORAL", "BUBBLE_CORAL_BLOCK",
            "BUBBLE_CORAL_FAN", "BUBBLE_CORAL_WALL_FAN", "BUCKET", "BUDDING_AMETHYST", "BUNDLE",
            "CACTUS", "CAKE", "CALCITE", "CAMPFIRE", "CANDLE", "CARROT", "CARROT_ON_A_STICK",
            "CARTOGRAPHY_TABLE", "CARVED_PUMPKIN", "CAT_SPAWN_EGG", "CAULDRON", "CAVE_SPIDER_SPAWN_EGG",
            "CHAIN", "CHAIN_COMMAND_BLOCK", "CHAINMAIL_BOOTS", "CHAINMAIL_CHESTPLATE", "CHAINMAIL_HELMET",
            "CHAINMAIL_LEGGINGS", "CHARCOAL", "CHEST", "CHEST_MINECART", "CHICKEN", "CHICKEN_SPAWN_EGG",
            "CHIPPED_ANVIL", "CHISELED_DEEPSLATE", "CHISELED_NETHER_BRICKS", "CHISELED_POLISHED_BLACKSTONE",
            "CHISELED_QUARTZ_BLOCK", "CHISELED_RED_SANDSTONE", "CHISELED_SANDSTONE", "CHISELED_STONE_BRICKS",
            "CHORUS_FLOWER", "CHORUS_FRUIT", "CHORUS_PLANT", "CLAY", "CLAY_BALL", "CLOCK", "COAL",
            "COAL_BLOCK", "COAL_ORE", "COARSE_DIRT", "COBBLED_DEEPSLATE", "COBBLED_DEEPSLATE_SLAB",
            "COBBLED_DEEPSLATE_STAIRS", "COBBLED_DEEPSLATE_WALL", "COBBLESTONE", "COBBLESTONE_SLAB",
            "COBBLESTONE_STAIRS", "COBBLESTONE_WALL", "COBWEB", "COCOA_BEANS", "COD",
            "COD_BUCKET", "COD_SPAWN_EGG", "COMMAND_BLOCK", "COMMAND_BLOCK_MINECART",
            "COMPARATOR", "COMPASS", "COMPOSTER", "CONDUIT", "COOKED_BEEF", "COOKED_CHICKEN",
            "COOKED_COD", "COOKED_MUTTON", "COOKED_PORKCHOP", "COOKED_RABBIT", "COOKED_SALMON",
            "COOKIE", "COPPER_BLOCK", "COPPER_INGOT", "COPPER_ORE", "CORNFLOWER", "COW_SPAWN_EGG",
            "CRACKED_DEEPSLATE_BRICKS", "CRACKED_DEEPSLATE_TILES", "CRACKED_NETHER_BRICKS",
            "CRACKED_POLISHED_BLACKSTONE_BRICKS", "CRACKED_STONE_BRICKS", "CRAFTING_TABLE",
            "CREEPER_BANNER_PATTERN", "CREEPER_HEAD", "CREEPER_SPAWN_EGG", "CREEPER_WALL_HEAD",
            "CRIMSON_BUTTON", "CRIMSON_DOOR", "CRIMSON_FENCE", "CRIMSON_FENCE_GATE", "CRIMSON_FUNGUS",
            "CRIMSON_HYPHAE", "CRIMSON_NYLIUM", "CRIMSON_PLANKS", "CRIMSON_PRESSURE_PLATE",
            "CRIMSON_ROOTS", "CRIMSON_SIGN", "CRIMSON_SLAB", "CRIMSON_STAIRS", "CRIMSON_STEM",
            "CRIMSON_TRAPDOOR", "CRIMSON_WALL_SIGN", "CROSSBOW", "CRYING_OBSIDIAN", "CUT_COPPER",
            "CUT_COPPER_SLAB", "CUT_COPPER_STAIRS", "CUT_RED_SANDSTONE", "CUT_RED_SANDSTONE_SLAB",
            "CUT_SANDSTONE", "CUT_SANDSTONE_SLAB", "CYAN_BANNER", "CYAN_BED", "CYAN_CANDLE",
            "CYAN_CARPET", "CYAN_CONCRETE", "CYAN_CONCRETE_POWDER", "CYAN_DYE", "CYAN_GLAZED_TERRACOTTA",
            "CYAN_SHULKER_BOX", "CYAN_STAINED_GLASS", "CYAN_STAINED_GLASS_PANE", "CYAN_TERRACOTTA",
            "CYAN_WOOL", "DAMAGED_ANVIL", "DANDELION", "DARK_OAK_BOAT", "DARK_OAK_BUTTON", "DARK_OAK_DOOR",
            "DARK_OAK_FENCE", "DARK_OAK_FENCE_GATE", "DARK_OAK_LEAVES", "DARK_OAK_LOG", "DARK_OAK_PLANKS",
            "DARK_OAK_PRESSURE_PLATE", "DARK_OAK_SAPLING", "DARK_OAK_SIGN", "DARK_OAK_SLAB", "DARK_OAK_STAIRS",
            "DARK_OAK_TRAPDOOR", "DARK_OAK_WALL_SIGN", "DARK_OAK_WOOD", "DARK_PRISMARINE", "DARK_PRISMARINE_SLAB",
            "DARK_PRISMARINE_STAIRS", "DAYLIGHT_DETECTOR", "DEAD_BRAIN_CORAL", "DEAD_BRAIN_CORAL_BLOCK",
            "DEAD_BRAIN_CORAL_FAN", "DEAD_BRAIN_CORAL_WALL_FAN", "DEAD_BUBBLE_CORAL", "DEAD_BUBBLE_CORAL_BLOCK",
            "DEAD_BUBBLE_CORAL_FAN", "DEAD_BUBBLE_CORAL_WALL_FAN", "DEAD_FIRE_CORAL", "DEAD_FIRE_CORAL_BLOCK",
            "DEAD_FIRE_CORAL_FAN", "DEAD_FIRE_CORAL_WALL_FAN", "DEAD_HORN_CORAL", "DEAD_HORN_CORAL_BLOCK",
            "DEAD_HORN_CORAL_FAN", "DEAD_HORN_CORAL_WALL_FAN", "DEAD_TUBE_CORAL", "DEAD_TUBE_CORAL_BLOCK",
            "DEAD_TUBE_CORAL_FAN", "DEAD_TUBE_CORAL_WALL_FAN", "DEBUG_STICK", "DEEPSLATE", "DEEPSLATE_BRICKS",
            "DEEPSLATE_BRICK_SLAB", "DEEPSLATE_BRICK_STAIRS", "DEEPSLATE_BRICK_WALL", "DEEPSLATE_COAL_ORE",
            "DEEPSLATE_COPPER_ORE", "DEEPSLATE_DIAMOND_ORE", "DEEPSLATE_EMERALD_ORE", "DEEPSLATE_GOLD_ORE",
            "DEEPSLATE_IRON_ORE", "DEEPSLATE_LAPIS_ORE", "DEEPSLATE_REDSTONE_ORE", "DEEPSLATE_TILES",
            "DEEPSLATE_TILE_SLAB", "DEEPSLATE_TILE_STAIRS", "DEEPSLATE_TILE_WALL", "DETECTOR_RAIL", "DIAMOND",
            "DIAMOND_AXE", "DIAMOND_BLOCK", "DIAMOND_BOOTS", "DIAMOND_CHESTPLATE", "DIAMOND_HELMET", "DIAMOND_HOE",
            "DIAMOND_HORSE_ARMOR", "DIAMOND_LEGGINGS", "DIAMOND_ORE", "DIAMOND_PICKAXE", "DIAMOND_SHOVEL",
            "DIAMOND_SWORD", "DIORITE", "DIORITE_SLAB", "DIORITE_STAIRS", "DIORITE_WALL", "DIRT", "DIRT_PATH",
            "DISPENSER", "DOLPHIN_SPAWN_EGG", "DONKEY_SPAWN_EGG", "DRAGON_BREATH", "DRAGON_EGG", "DRAGON_HEAD",
            "DRAGON_WALL_HEAD", "DRIED_KELP", "DRIED_KELP_BLOCK", "DRIPSTONE_BLOCK", "DROPPER", "DROWNED_SPAWN_EGG",
            "EGG", "ELDER_GUARDIAN_SPAWN_EGG", "ELYTRA", "EMERALD", "EMERALD_BLOCK", "EMERALD_ORE", "ENCHANTED_BOOK",
            "ENCHANTED_GOLDEN_APPLE", "ENCHANTING_TABLE", "ENDERMAN_SPAWN_EGG", "ENDERMITE_SPAWN_EGG", "ENDER_CHEST",
            "ENDER_EYE", "ENDER_PEARL", "END_CRYSTAL", "END_GATEWAY", "END_PORTAL", "END_PORTAL_FRAME", "END_ROD",
            "END_STONE", "END_STONE_BRICKS", "END_STONE_BRICK_SLAB", "END_STONE_BRICK_STAIRS", "END_STONE_BRICK_WALL",
            "EVOKER_SPAWN_EGG", "EXPERIENCE_BOTTLE", "EXPOSED_COPPER", "EXPOSED_CUT_COPPER", "EXPOSED_CUT_COPPER_SLAB",
            "EXPOSED_CUT_COPPER_STAIRS", "FARMLAND", "FEATHER", "FERMENTED_SPIDER_EYE", "FERN", "FILLED_MAP",
            "FIRE", "FIREWORK_ROCKET", "FIREWORK_STAR", "FIRE_CHARGE", "FIRE_CORAL", "FIRE_CORAL_BLOCK", "FIRE_CORAL_FAN",
            "FIRE_CORAL_WALL_FAN", "FISHING_ROD", "FLETCHING_TABLE", "FLINT", "FLINT_AND_STEEL", "FLOWER_BANNER_PATTERN",
            "FLOWER_POT", "FOX_SPAWN_EGG", "FROG_SPAWN_EGG", "FROSTED_ICE", "FURNACE", "FURNACE_MINECART",
            "GHAST_SPAWN_EGG", "GHAST_TEAR", "GILDED_BLACKSTONE", "GLASS", "GLASS_BOTTLE", "GLASS_PANE",
            "GLISTERING_MELON_SLICE", "GLOBE_BANNER_PATTERN", "GLOWSTONE", "GLOWSTONE_DUST", "GLOW_BERRIES",
            "GLOW_INK_SAC", "GLOW_ITEM_FRAME", "GLOW_LICHEN", "GLOW_SQUID_SPAWN_EGG", "GOAT_SPAWN_EGG", "GOLDEN_APPLE",
            "GOLDEN_AXE", "GOLDEN_BOOTS", "GOLDEN_CARROT", "GOLDEN_CHESTPLATE", "GOLDEN_HELMET", "GOLDEN_HOE",
            "GOLDEN_HORSE_ARMOR", "GOLDEN_LEGGINGS", "GOLDEN_PICKAXE", "GOLDEN_SHOVEL", "GOLDEN_SWORD", "GOLD_BLOCK",
            "GOLD_INGOT", "GOLD_NUGGET", "GOLD_ORE", "GRANITE", "GRANITE_SLAB", "GRANITE_STAIRS", "GRANITE_WALL",
            "GRASS", "GRASS_BLOCK", "GRAVEL", "GRAY_BANNER", "GRAY_BED", "GRAY_CANDLE", "GRAY_CARPET", "GRAY_CONCRETE",
            "GRAY_CONCRETE_POWDER", "GRAY_DYE", "GRAY_GLAZED_TERRACOTTA", "GRAY_SHULKER_BOX", "GRAY_STAINED_GLASS",
            "GRAY_STAINED_GLASS_PANE", "GRAY_TERRACOTTA", "GRAY_WOOL", "GREEN_BANNER", "GREEN_BED", "GREEN_CANDLE",
            "GREEN_CARPET", "GREEN_CONCRETE", "GREEN_CONCRETE_POWDER", "GREEN_DYE", "GREEN_GLAZED_TERRACOTTA",
            "GREEN_SHULKER_BOX", "GREEN_STAINED_GLASS", "GREEN_STAINED_GLASS_PANE", "GREEN_TERRACOTTA", "GREEN_WOOL",
            "GRINDSTONE", "GUARDIAN_SPAWN_EGG", "GUNPOWDER", "HANGING_ROOTS", "HAY_BLOCK", "HEART_OF_THE_SEA",
            "HEAVY_WEIGHTED_PRESSURE_PLATE", "HOGLIN_SPAWN_EGG", "HONEYCOMB", "HONEYCOMB_BLOCK", "HONEY_BLOCK",
            "HONEY_BOTTLE", "HOPPER", "HOPPER_MINECART", "HORN_CORAL", "HORN_CORAL_BLOCK", "HORN_CORAL_FAN",
            "HORN_CORAL_WALL_FAN", "HORSE_SPAWN_EGG", "HUSK_SPAWN_EGG", "ICE", "INFESTED_CHISELED_STONE_BRICKS",
            "INFESTED_COBBLESTONE", "INFESTED_CRACKED_STONE_BRICKS", "INFESTED_DEEPSLATE", "INFESTED_MOSSY_STONE_BRICKS",
            "INFESTED_STONE", "INFESTED_STONE_BRICKS", "INK_SAC", "IRON_AXE", "IRON_BARS", "IRON_BLOCK", "IRON_BOOTS",
            "IRON_CHESTPLATE", "IRON_DOOR", "IRON_GOLEM_SPAWN_EGG", "IRON_HELMET", "IRON_HOE", "IRON_HORSE_ARMOR",
            "IRON_INGOT", "IRON_LEGGINGS", "IRON_NUGGET", "IRON_ORE", "IRON_PICKAXE",             "IRON_SHOVEL", "IRON_SWORD", "IRON_TRAPDOOR", "ITEM_FRAME", "JACK_O_LANTERN", "JIGSAW", "JUKEBOX",
            "JUNGLE_BOAT", "JUNGLE_BUTTON", "JUNGLE_DOOR", "JUNGLE_FENCE", "JUNGLE_FENCE_GATE", "JUNGLE_LEAVES",
            "JUNGLE_LOG", "JUNGLE_PLANKS", "JUNGLE_PRESSURE_PLATE", "JUNGLE_SAPLING", "JUNGLE_SIGN", "JUNGLE_SLAB",
            "JUNGLE_STAIRS", "JUNGLE_TRAPDOOR", "JUNGLE_WALL_SIGN", "JUNGLE_WOOD", "KELP", "KELP_PLANT", "KNOWLEDGE_BOOK",
            "LADDER", "LANTERN", "LAPIS_BLOCK", "LAPIS_LAZULI", "LAPIS_ORE", "LARGE_AMETHYST_BUD", "LARGE_FERN",
            "LAVA", "LAVA_BUCKET", "LAVA_CAULDRON", "LEAD", "LEATHER", "LEATHER_BOOTS", "LEATHER_CHESTPLATE",
            "LEATHER_HELMET", "LEATHER_HORSE_ARMOR", "LEATHER_LEGGINGS", "LECTERN", "LEVER", "LIGHT", "LIGHT_BLUE_BANNER",
            "LIGHT_BLUE_BED", "LIGHT_BLUE_CANDLE", "LIGHT_BLUE_CARPET", "LIGHT_BLUE_CONCRETE", "LIGHT_BLUE_CONCRETE_POWDER",
            "LIGHT_BLUE_DYE", "LIGHT_BLUE_GLAZED_TERRACOTTA", "LIGHT_BLUE_SHULKER_BOX", "LIGHT_BLUE_STAINED_GLASS",
            "LIGHT_BLUE_STAINED_GLASS_PANE", "LIGHT_BLUE_TERRACOTTA", "LIGHT_BLUE_WOOL", "LIGHT_GRAY_BANNER",
            "LIGHT_GRAY_BED", "LIGHT_GRAY_CANDLE", "LIGHT_GRAY_CARPET", "LIGHT_GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE_POWDER",
            "LIGHT_GRAY_DYE", "LIGHT_GRAY_GLAZED_TERRACOTTA", "LIGHT_GRAY_SHULKER_BOX", "LIGHT_GRAY_STAINED_GLASS",
            "LIGHT_GRAY_STAINED_GLASS_PANE", "LIGHT_GRAY_TERRACOTTA", "LIGHT_GRAY_WOOL", "LIGHT_WEIGHTED_PRESSURE_PLATE",
            "LIGHTNING_ROD", "LILAC", "LILY_OF_THE_VALLEY", "LILY_PAD", "LIME_BANNER", "LIME_BED", "LIME_CANDLE",
            "LIME_CARPET", "LIME_CONCRETE", "LIME_CONCRETE_POWDER", "LIME_DYE", "LIME_GLAZED_TERRACOTTA", "LIME_SHULKER_BOX",
            "LIME_STAINED_GLASS", "LIME_STAINED_GLASS_PANE", "LIME_TERRACOTTA", "LIME_WOOL", "LINGERING_POTION",
            "LLAMA_SPAWN_EGG", "LODESTONE", "LOOM", "MAGENTA_BANNER", "MAGENTA_BED", "MAGENTA_CANDLE", "MAGENTA_CARPET",
            "MAGENTA_CONCRETE", "MAGENTA_CONCRETE_POWDER", "MAGENTA_DYE", "MAGENTA_GLAZED_TERRACOTTA", "MAGENTA_SHULKER_BOX",
            "MAGENTA_STAINED_GLASS", "MAGENTA_STAINED_GLASS_PANE", "MAGENTA_TERRACOTTA", "MAGENTA_WOOL", "MAGMA_BLOCK",
            "MAGMA_CREAM", "MAGMA_CUBE_SPAWN_EGG", "MAP", "MEDIUM_AMETHYST_BUD", "MELON", "MELON_SEEDS", "MELON_SLICE",
            "MILK_BUCKET", "MINECART", "MOJANG_BANNER_PATTERN", "MOOSHROOM_SPAWN_EGG", "MOSS_BLOCK", "MOSS_CARPET",
            "MOSSY_COBBLESTONE", "MOSSY_COBBLESTONE_SLAB", "MOSSY_COBBLESTONE_STAIRS", "MOSSY_COBBLESTONE_WALL",
            "MOSSY_STONE_BRICKS", "MOSSY_STONE_BRICK_SLAB", "MOSSY_STONE_BRICK_STAIRS", "MOSSY_STONE_BRICK_WALL",
            "MOVING_PISTON", "MUD", "MUD_BRICKS", "MUD_BRICK_SLAB", "MUD_BRICK_STAIRS", "MUD_BRICK_WALL", "MUDDY_MANGROVE_ROOTS",
            "MULE_SPAWN_EGG", "MUSHROOM_STEM", "MUSHROOM_STEW", "MUSIC_DISC_11", "MUSIC_DISC_13", "MUSIC_DISC_BLOCKS",
            "MUSIC_DISC_CAT", "MUSIC_DISC_CHIRP", "MUSIC_DISC_FAR", "MUSIC_DISC_MALL", "MUSIC_DISC_MELLOHI", "MUSIC_DISC_OTHERSIDE",
            "MUSIC_DISC_PIGSTEP", "MUSIC_DISC_STAL", "MUSIC_DISC_STRAD", "MUSIC_DISC_WAIT", "MUSIC_DISC_WARD", "MUTTON",
            "MYCELIUM", "NAME_TAG", "Nautilus_SHELL", "NETHER_BRICK", "NETHER_BRICKS", "NETHER_BRICK_FENCE", "NETHER_BRICK_SLAB",
            "NETHER_BRICK_STAIRS", "NETHER_BRICK_WALL", "NETHER_GOLD_ORE", "NETHER_QUARTZ_ORE", "NETHER_SPROUTS", "NETHER_STAR",
            "NETHER_WART", "NETHER_WART_BLOCK", "NETHERITE_AXE", "NETHERITE_BLOCK", "NETHERITE_BOOTS", "NETHERITE_CHESTPLATE",
            "NETHERITE_HELMET", "NETHERITE_HOE", "NETHERITE_INGOT", "NETHERITE_LEGGINGS", "NETHERITE_PICKAXE", "NETHERITE_SCRAP",
            "NETHERITE_SHOVEL", "NETHERITE_SWORD", "NETHERRACK", "NOTE_BLOCK", "OAK_BOAT", "OAK_BUTTON", "OAK_DOOR", "OAK_FENCE",
            "OAK_FENCE_GATE", "OAK_LEAVES", "OAK_LOG", "OAK_PLANKS", "OAK_PRESSURE_PLATE", "OAK_SAPLING", "OAK_SIGN", "OAK_SLAB",
            "OAK_STAIRS", "OAK_TRAPDOOR", "OAK_WALL_SIGN", "OAK_WOOD", "OBSERVER", "OBSIDIAN", "OCELOT_SPAWN_EGG", "ORANGE_BANNER",
            "ORANGE_BED", "ORANGE_CANDLE", "ORANGE_CARPET", "ORANGE_CONCRETE", "ORANGE_CONCRETE_POWDER", "ORANGE_DYE",
            "ORANGE_GLAZED_TERRACOTTA", "ORANGE_SHULKER_BOX", "ORANGE_STAINED_GLASS", "ORANGE_STAINED_GLASS_PANE",
            "ORANGE_TERRACOTTA", "ORANGE_TULIP", "ORANGE_WOOL", "OXEYE_DAISY", "PACKED_ICE", "PAINTING", "PANDA_SPAWN_EGG",
            "PAPER", "PARROT_SPAWN_EGG", "PEONY", "PETRIFIED_OAK_SLAB", "PHANTOM_MEMBRANE", "PHANTOM_SPAWN_EGG",
            "PIG_SPAWN_EGG", "PIGLIN_BANNER_PATTERN", "PIGLIN_BRUTE_SPAWN_EGG", "PIGLIN_SPAWN_EGG", "PILLAGER_SPAWN_EGG",
            "PINK_BANNER", "PINK_BED", "PINK_CANDLE", "PINK_CARPET", "PINK_CONCRETE", "PINK_CONCRETE_POWDER", "PINK_DYE",
            "PINK_GLAZED_TERRACOTTA", "PINK_SHULKER_BOX", "PINK_STAINED_GLASS", "PINK_STAINED_GLASS_PANE", "PINK_TERRACOTTA",
            "PINK_TULIP", "PINK_WOOL", "PISTON", "PISTON_HEAD", "PLAYER_HEAD", "PLAYER_WALL_HEAD", "PODZOL", "POINTED_DRIPSTONE",
            "POISONOUS_POTATO", "POLAR_BEAR_SPAWN_EGG", "POLISHED_ANDESITE", "POLISHED_ANDESITE_SLAB", "POLISHED_ANDESITE_STAIRS",
            "POLISHED_BASALT", "POLISHED_BLACKSTONE", "POLISHED_BLACKSTONE_BRICKS", "POLISHED_BLACKSTONE_BRICK_SLAB",
            "POLISHED_BLACKSTONE_BRICK_STAIRS", "POLISHED_BLACKSTONE_BRICK_WALL", "POLISHED_BLACKSTONE_BUTTON", "POLISHED_BLACKSTONE_PRESSURE_PLATE",
            "POLISHED_BLACKSTONE_SLAB", "POLISHED_BLACKSTONE_STAIRS", "POLISHED_BLACKSTONE_WALL", "POLISHED_DEEPSLATE",
            "POLISHED_DEEPSLATE_SLAB",             "POLISHED_DEEPSLATE_STAIRS", "POLISHED_DEEPSLATE_WALL", "POLISHED_DIORITE", "POLISHED_DIORITE_SLAB",
            "POLISHED_DIORITE_STAIRS", "POLISHED_GRANITE", "POLISHED_GRANITE_SLAB", "POLISHED_GRANITE_STAIRS",
            "POPPY", "PORKCHOP", "POTATO", "POTION", "POWDER_SNOW", "POWDER_SNOW_BUCKET", "POWDER_SNOW_CAULDRON",
            "POWERED_RAIL", "PRISMARINE", "PRISMARINE_BRICKS", "PRISMARINE_BRICK_SLAB", "PRISMARINE_BRICK_STAIRS",
            "PRISMARINE_CRYSTALS", "PRISMARINE_SHARD", "PRISMARINE_SLAB", "PRISMARINE_STAIRS", "PRISMARINE_WALL",
            "PUFFERFISH", "PUFFERFISH_BUCKET", "PUFFERFISH_SPAWN_EGG", "PUMPKIN", "PUMPKIN_PIE", "PUMPKIN_SEEDS",
            "PURPLE_BANNER", "PURPLE_BED", "PURPLE_CANDLE", "PURPLE_CARPET", "PURPLE_CONCRETE", "PURPLE_CONCRETE_POWDER",
            "PURPLE_DYE", "PURPLE_GLAZED_TERRACOTTA", "PURPLE_SHULKER_BOX", "PURPLE_STAINED_GLASS", "PURPLE_STAINED_GLASS_PANE",
            "PURPLE_TERRACOTTA", "PURPLE_WOOL", "PURPUR_BLOCK", "PURPUR_PILLAR", "PURPUR_SLAB", "PURPUR_STAIRS",
            "QUARTZ", "QUARTZ_BLOCK", "QUARTZ_BRICKS", "QUARTZ_PILLAR", "QUARTZ_SLAB", "QUARTZ_STAIRS", "RABBIT",
            "RABBIT_FOOT", "RABBIT_HIDE", "RABBIT_SPAWN_EGG", "RABBIT_STEW", "RAIL", "RAVAGER_SPAWN_EGG",
            "RAW_COPPER", "RAW_COPPER_BLOCK", "RAW_GOLD", "RAW_GOLD_BLOCK", "RAW_IRON", "RAW_IRON_BLOCK", "REDSTONE",
            "REDSTONE_BLOCK", "REDSTONE_LAMP", "REDSTONE_ORE", "REDSTONE_TORCH", "REDSTONE_WALL_TORCH", "REDSTONE_WIRE",
            "RED_BANNER", "RED_BED", "RED_CANDLE", "RED_CARPET", "RED_CONCRETE", "RED_CONCRETE_POWDER", "RED_DYE",
            "RED_GLAZED_TERRACOTTA", "RED_MUSHROOM", "RED_MUSHROOM_BLOCK", "RED_NETHER_BRICKS", "RED_NETHER_BRICK_SLAB",
            "RED_NETHER_BRICK_STAIRS", "RED_NETHER_BRICK_WALL", "RED_SAND", "RED_SANDSTONE", "RED_SANDSTONE_SLAB",
            "RED_SANDSTONE_STAIRS", "RED_SANDSTONE_WALL", "RED_SHULKER_BOX", "RED_STAINED_GLASS", "RED_STAINED_GLASS_PANE",
            "RED_TERRACOTTA", "RED_TULIP", "RED_WOOL", "REINFORCED_DEEPSLATE", "REPEATER", "REPEATING_COMMAND_BLOCK",
            "ROOTED_DIRT", "ROSE_BUSH", "ROTTEN_FLESH", "SADDLE", "SALMON", "SALMON_BUCKET", "SALMON_SPAWN_EGG",
            "SAND", "SANDSTONE", "SANDSTONE_SLAB", "SANDSTONE_STAIRS", "SANDSTONE_WALL", "SCAFFOLDING", "SCULK_SENSOR",
            "SCUTE", "SEA_LANTERN", "SEA_PICKLE", "SHEARS", "SHEEP_SPAWN_EGG", "SHIELD", "SHROOMLIGHT", "SHULKER_BOX",
            "SHULKER_SHELL", "SHULKER_SPAWN_EGG", "SILVERFISH_SPAWN_EGG", "SKELETON_HORSE_SPAWN_EGG", "SKELETON_SKULL",
            "SKELETON_SPAWN_EGG", "SKELETON_WALL_SKULL", "SKULL_BANNER_PATTERN", "SLIME_BALL", "SLIME_BLOCK",
            "SLIME_SPAWN_EGG", "SMALL_AMETHYST_BUD", "SMALL_DRIPLEAF", "SMITHING_TABLE", "SMOKER", "SMOOTH_BASALT",
            "SMOOTH_QUARTZ", "SMOOTH_QUARTZ_SLAB", "SMOOTH_QUARTZ_STAIRS", "SMOOTH_RED_SANDSTONE", "SMOOTH_RED_SANDSTONE_SLAB",
            "SMOOTH_RED_SANDSTONE_STAIRS", "SMOOTH_SANDSTONE", "SMOOTH_SANDSTONE_SLAB", "SMOOTH_SANDSTONE_STAIRS",
            "SMOOTH_STONE", "SMOOTH_STONE_SLAB", "SNOW", "SNOWBALL", "SNOW_BLOCK", "SOUL_CAMPFIRE", "SOUL_FIRE",
            "SOUL_LANTERN", "SOUL_SAND", "SOUL_SOIL", "SOUL_TORCH", "SOUL_WALL_TORCH", "SPAWNER", "SPECTRAL_ARROW",
            "SPIDER_EYE", "SPIDER_SPAWN_EGG", "SPLASH_POTION", "SPONGE", "SPORE_BLOSSOM", "SPRUCE_BOAT", "SPRUCE_BUTTON",
            "SPRUCE_DOOR", "SPRUCE_FENCE", "SPRUCE_FENCE_GATE", "SPRUCE_LEAVES", "SPRUCE_LOG", "SPRUCE_PLANKS",
            "SPRUCE_PRESSURE_PLATE", "SPRUCE_SAPLING", "SPRUCE_SIGN", "SPRUCE_SLAB", "SPRUCE_STAIRS", "SPRUCE_TRAPDOOR",
            "SPRUCE_WALL_SIGN", "SPRUCE_WOOD", "SPYGLASS", "SQUID_SPAWN_EGG", "STICK", "STICKY_PISTON", "STONE",
            "STONE_AXE", "STONE_BRICKS", "STONE_BRICK_SLAB", "STONE_BRICK_STAIRS", "STONE_BRICK_WALL", "STONE_BUTTON",
            "STONE_HOE", "STONE_PICKAXE", "STONE_PRESSURE_PLATE", "STONE_SHOVEL", "STONE_SLAB", "STONE_STAIRS",
            "STONE_SWORD", "STRAY_SPAWN_EGG", "STRING", "STRIPPED_ACACIA_LOG", "STRIPPED_ACACIA_WOOD", "STRIPPED_BIRCH_LOG",
            "STRIPPED_BIRCH_WOOD", "STRIPPED_CRIMSON_HYPHAE", "STRIPPED_CRIMSON_STEM", "STRIPPED_DARK_OAK_LOG",
            "STRIPPED_DARK_OAK_WOOD", "STRIPPED_JUNGLE_LOG", "STRIPPED_JUNGLE_WOOD", "STRIPPED_OAK_LOG",
            "STRIPPED_OAK_WOOD", "STRIPPED_SPRUCE_LOG", "STRIPPED_SPRUCE_WOOD", "STRIPPED_WARPED_HYPHAE",
            "STRIPPED_WARPED_STEM", "STRUCTURE_BLOCK", "STRUCTURE_VOID", "SUGAR", "SUGAR_CANE", "SUNFLOWER", "SUSPICIOUS_STEW",
            "SWEET_BERRIES", "TADPOLE_BUCKET", "TADPOLE_SPAWN_EGG", "TERRACOTTA", "TINTED_GLASS", "TIPPED_ARROW",
            "TNT", "TNT_MINECART", "TORCH", "TOTEM_OF_UNDYING", "TRADER_LLAMA_SPAWN_EGG", "TRAPPED_CHEST", "TRIDENT",
            "TROPICAL_FISH", "TROPICAL_FISH_BUCKET", "TROPICAL_FISH_SPAWN_EGG", "TUBE_CORAL", "TUBE_CORAL_BLOCK",
            "TUBE_CORAL_FAN", "TUBE_CORAL_WALL_FAN", "TUFF", "TURTLE_EGG", "TURTLE_HELMET", "TURTLE_SPAWN_EGG",
            "TWISTING_VINES", "VERDANT_FROGLIGHT", "VEX_SPAWN_EGG", "VILLAGER_SPAWN_EGG", "VINDICATOR_SPAWN_EGG",
            "VINE", "VOID_AIR", "WALL_TORCH", "WANDERING_TRADER_SPAWN_EGG", "WARPED_BUTTON", "WARPED_DOOR",
            "WARPED_FENCE", "WARPED_FENCE_GATE", "WARPED_FUNGUS", "WARPED_FUNGUS_ON_A_STICK", "WARPED_HYPHAE",
            "WARPED_NYLIUM", "WARPED_PLANKS", "WARPED_PRESSURE_PLATE", "WARPED_ROOTS",             "WARPED_SIGN", "WARPED_SLAB", "WARPED_STAIRS", "WARPED_STEM", "WARPED_TRAPDOOR", "WARPED_WALL_SIGN",
            "WARPED_WART_BLOCK", "WATER", "WATER_BUCKET", "WATER_CAULDRON", "WAXED_COPPER_BLOCK", "WAXED_CUT_COPPER",
            "WAXED_CUT_COPPER_SLAB", "WAXED_CUT_COPPER_STAIRS", "WAXED_EXPOSED_COPPER", "WAXED_EXPOSED_CUT_COPPER",
            "WAXED_EXPOSED_CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_COPPER", "WAXED_OXIDIZED_CUT_COPPER",
            "WAXED_OXIDIZED_CUT_COPPER_SLAB", "WAXED_OXIDIZED_CUT_COPPER_STAIRS", "WAXED_WEATHERED_COPPER", "WAXED_WEATHERED_CUT_COPPER",
            "WAXED_WEATHERED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_STAIRS", "WEATHERED_COPPER", "WEATHERED_CUT_COPPER",
            "WEATHERED_CUT_COPPER_SLAB", "WEATHERED_CUT_COPPER_STAIRS", "WEB", "WEEPING_VINES", "WET_SPONGE", "WHEAT",
            "WHEAT_SEEDS", "WHITE_BANNER", "WHITE_BED", "WHITE_CANDLE", "WHITE_CARPET", "WHITE_CONCRETE", "WHITE_CONCRETE_POWDER",
            "WHITE_DYE", "WHITE_GLAZED_TERRACOTTA", "WHITE_SHULKER_BOX", "WHITE_STAINED_GLASS", "WHITE_STAINED_GLASS_PANE",
            "WHITE_TERRACOTTA", "WHITE_TULIP", "WHITE_WOOL", "WITCH_SPAWN_EGG", "WITHER_ROSE", "WITHER_SKELETON_SKULL",
            "WITHER_SKELETON_SPAWN_EGG", "WITHER_SKELETON_WALL_SKULL", "WOLF_SPAWN_EGG", "WOODEN_AXE", "WOODEN_HOE",
            "WOODEN_PICKAXE", "WOODEN_SHOVEL", "WOODEN_SWORD", "WRITABLE_BOOK", "WRITTEN_BOOK", "YELLOW_BANNER",
            "YELLOW_BED", "YELLOW_CANDLE", "YELLOW_CARPET", "YELLOW_CONCRETE", "YELLOW_CONCRETE_POWDER", "YELLOW_DYE",
            "YELLOW_GLAZED_TERRACOTTA", "YELLOW_SHULKER_BOX", "YELLOW_STAINED_GLASS", "YELLOW_STAINED_GLASS_PANE",
            "YELLOW_TERRACOTTA", "YELLOW_WOOL", "ZOGLIN_SPAWN_EGG", "ZOMBIE_HEAD", "ZOMBIE_HORSE_SPAWN_EGG", "ZOMBIE_SPAWN_EGG",
            "ZOMBIE_VILLAGER_SPAWN_EGG", "ZOMBIFIED_PIGLIN_SPAWN_EGG"
        }

    def create_widgets(self):
        # Left frame for crafting grid and input
        left_frame = ttk.Frame(self.root)
        left_frame.grid(row=0, column=0, padx=10, pady=10)

        # Crafting grid
        self.entries = []
        for i in range(3):
            row_entries = []
            for j in range(3):
                entry = ttk.Entry(left_frame, width=10)
                entry.grid(row=i, column=j, padx=5, pady=5)
                entry.bind("<KeyRelease>", self.update_display)  # Update on key release
                row_entries.append(entry)
            self.entries.append(row_entries)
        
        # Custom item result entry
        tk.Label(left_frame, text="Custom Item Result:").grid(row=3, column=0, pady=10, columnspan=3)
        self.result_entry = ttk.Entry(left_frame, width=20)
        self.result_entry.grid(row=4, column=0, pady=10, columnspan=3)
        self.result_entry.bind("<KeyRelease>", self.update_display)  # Update on key release

        # Copy button
        copy_button = ttk.Button(left_frame, text="Copy Config", command=self.copy_config)
        copy_button.grid(row=5, column=0, columnspan=3, pady=10)

        # Clear button
        clear_button = ttk.Button(left_frame, text="Clear", command=self.clear_all)
        clear_button.grid(row=6, column=0, columnspan=3, pady=10)

        # Right frame for config display
        right_frame = ttk.Frame(self.root)
        right_frame.grid(row=0, column=1, padx=10, pady=10, sticky='n')

        # Config display
        self.config_display = tk.Text(right_frame, width=40, height=20, wrap='word')
        self.config_display.grid(row=0, column=0, padx=5, pady=5)
        self.config_display.config(state=tk.DISABLED)

    def copy_config(self):
        self.extract_crafting_grid()
        custom_item = self.result_entry.get().strip()
        if not custom_item:
            messagebox.showerror("Error", "Custom item result cannot be empty!")
            return

        ingredients, pattern = self.construct_ingredients_and_pattern()
        config = self.construct_config(custom_item, ingredients, pattern)

        self.root.clipboard_clear()
        self.root.clipboard_append(f"    {self.get_item_name(custom_item)}:\n{config}")
        messagebox.showinfo("Success", "Config copied to clipboard!")

    def extract_crafting_grid(self):
        for i in range(3):
            for j in range(3):
                self.crafting_grid[i][j] = self.entries[i][j].get().strip()

    def construct_ingredients_and_pattern(self):
        ingredients = {}
        pattern = []
        current_letter = ord('B')  # Start from 'B'
        
        for i, row in enumerate(self.crafting_grid):
            pattern_row = ''
            for j, item in enumerate(row):
                entry = self.entries[i][j]
                if item:
                    if item in self.valid_item_ids:
                        entry.config(foreground="green")
                    else:
                        entry.config(foreground="red")
                    if item not in ingredients:
                        if current_letter > ord('Z'):
                            messagebox.showerror("Error", "Too many unique items in the recipe.")
                            return None, None
                        ingredients[item] = chr(current_letter)
                        current_letter += 1
                    pattern_row += ingredients[item]
                else:
                    entry.config(foreground="black")
                    pattern_row += 'X'
            pattern.append(pattern_row)
        return ingredients, pattern

    def construct_config(self, custom_item, ingredients, pattern):
        ingredients_config = "\n".join([f"        {value}: {key}" for key, value in ingredients.items()])
        pattern_config = "\n".join([f"      - {row}" for row in pattern])
        config = f"""      permission: rangemc.crafting
      enabled: true
      pattern:
{pattern_config}
      ingredients:
{ingredients_config}
      result:
        item: {custom_item}
        amount: 1"""
        return config

    def get_item_name(self, custom_item):
        if ":" in custom_item:
            return custom_item.split(":")[1]
        return custom_item

    def update_display(self, event=None):
        self.extract_crafting_grid()
        custom_item = self.result_entry.get().strip()
        ingredients, pattern = self.construct_ingredients_and_pattern()
        if ingredients is None or pattern is None:
            return  # Stop update if there is an error
        config = self.construct_config(custom_item, ingredients, pattern)
        
        self.config_display.config(state=tk.NORMAL)
        self.config_display.delete(1.0, tk.END)
        self.config_display.insert(tk.END, f"    {self.get_item_name(custom_item)}:\n{config}")
        self.config_display.config(state=tk.DISABLED)

    def clear_all(self):
        # Clear all entry fields
        for row in self.entries:
            for entry in row:
                entry.delete(0, tk.END)
        self.result_entry.delete(0, tk.END)
        # Clear the config display
        self.config_display.config(state=tk.NORMAL)
        self.config_display.delete(1.0, tk.END)
        self.config_display.config(state=tk.DISABLED)
        # Clear the crafting grid and ingredients
        self.crafting_grid = [['' for _ in range(3)] for _ in range(3)]
        self.ingredients = {}

if __name__ == "__main__":
    root = tk.Tk()
    app = RecipeConfigurator(root)
    root.mainloop()